title: Управление категориями
modelClass: Bronx\Project\Models\Category
list: $/bronx/project/models/category/columns.yaml
recordUrl: bronx/project/categories/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showPageNumbers: true
showSetup: true
showSorting: true
showCheckboxes: true
showTree: true
treeExpanded: true

toolbar:
    buttons: list_toolbar

    search:
        prompt: backend::lang.list.search_prompt